server:
  # porta di Default di Eureka Server
  port: 8761

spring:
  application:
    name: msdiscovery

eureka:
  client:
    # https://www.javaboss.it/eureka-service-registry/
    #serviceUrl:
    #  defaultZone: http://localhost:8761/eureka/
    # eureka non registra se stessa
    register-with-eureka: false
    # non passo informazioni su me stesso a me stesso
    fetch-registry: false
  # quando trovo un ms, come lo registro:
  instance:
    # lo registro per indirizzo ip (piuttosto che il nome riportato dal sistema operativo)
    prefer-ip-address: true
    hostname: localhost
